apiVersion: v1
kind: Service
metadata:
  name: cortex-neo4j
  namespace: cortex
  labels:
    app.kubernetes.io/name: cortex
    app.kubernetes.io/component: neo4j
spec:
  type: ClusterIP
  ports:
    - port: 7474
      targetPort: 7474
      name: http
    - port: 7687
      targetPort: 7687
      name: bolt
  selector:
    app.kubernetes.io/name: cortex
    app.kubernetes.io/component: neo4j
